# template for "Guess the number" mini-project
# input will come from buttons and an input field
# all output for the game will be printed in the console

import math
import random
import simplegui

# initialize global variables used in your code

# For example, one obvious choice is the secret number that has been 
# generated by the program. You will need other global variables, 
# especially to accommodate later extensions to the basic game.

secret_number = 0
number_of_guesses = 0
range_high = 100


# helper function to start and restart the game
def new_game():
    global range_high, secret_number, number_of_guesses
    secret_number = generate_secret_number(0, range_high + 1)
    if range_high == 100:
        number_of_guesses = 7
    else:
        number_of_guesses = 10
        
    print "New Game. Number of guesses:", number_of_guesses, " Range:", range_high

def generate_secret_number(low, high):
    return random.randrange(low, high + 1)
    
# define event handlers for control panel
def range100():
    global range_high
    # button that changes range to range [0,100) and restarts
    range_high = 100
    new_game()
    

def range1000():
    global range_high
    # button that changes range to range [0,1000) and restarts
    range_high = 1000
    new_game()
    
    
def input_guess(guess):
    global range_high, secret_number, number_of_guesses 
    # main game logic goes here	
    number = int(guess)
    print "Your guess number:", number
    if number < secret_number:
        print "Higher!"
    elif number > secret_number:
        print "Lower!"
    else:
        print "Correct!"
        print "You won!"
        new_game()
    
    number_of_guesses = number_of_guesses - 1
    print "guesses remaining:", number_of_guesses
    if number_of_guesses == 0:
        print "Game Over!!!"
        new_game()
    
    
# create frame
f = simplegui.create_frame("Guess the number!",300,300)


# register event handlers for control elements
f.add_input("Enter your guess", input_guess, 100)
f.add_button("Range 100", range100, 100)
f.add_button("Range 1000", range1000, 100)

# call new_game and start frame
random.seed()
new_game()
f.start()


# always remember to check your completed program against the grading rubric
